/*
 * @Author: zdenzel
 * @Date:   2018-03-14 23:37:54
 * @Last Modified by:   denzel
 * @Last Modified time: 2018-05-05 14:56:33
 */

export default {

    SHOP_CART_LIST: 'SHOP_CART_LIST',
    GET_SHOP_CART_LIST: 'GET_SHOP_CART_LIST',
    SET_SHOP_CART_LIST: 'SET_SHOP_CART_LIST',
    ADD_SHOP_CART_LIST: 'ADD_SHOP_CART_LIST',
    DEL_SHOP_CART_LIST: 'DEL_SHOP_CART_LIST',
    CHECK_SHOP_CART_ONE: 'CHECK_SHOP_CART_ONE',
    CHECK_SHOP_CART_ALL: 'CHECK_SHOP_CART_ALL',

    SHOP_BUY_LIST: 'SHOP_BUY_LIST',
    SET_SHOP_BUY_LIST: 'SET_SHOP_BUY_LIST',
    GET_SHOP_BUY_LIST: 'GET_SHOP_BUY_LIST',
    DEL_SHOP_BUY_LIST: 'DEL_SHOP_BUY_LIST',

    SHOP_BUY_CONSIGNEE: 'SHOP_BUY_CONSIGNEE',
    SET_SHOP_BUY_CONSIGNEE: 'SET_SHOP_BUY_CONSIGNEE',
    GET_SHOP_BUY_CONSIGNEE: 'GET_SHOP_BUY_CONSIGNEE',
    DEL_SHOP_BUY_CONSIGNEE: 'DEL_SHOP_BUY_CONSIGNEE',

}